export const FETCH_CAR_DETAILS_START = 'FETCH_CAR_DETAILS_START';
export const FETCH_CAR_DETAILS_SUCCESS = 'FETCH_CAR_DETAILS_SUCCESS';
export const FETCH_CAR_DETAILS_FAILURE = 'FETCH_CAR_DETAILS_FAILURE';

export const FETCH_CAR_LIST_START = 'FETCH_CAR_LIST_START';
export const FETCH_CAR_LIST_SUCCESS = 'FETCH_CAR_LIST_SUCCESS';
export const FETCH_CAR_LIST_FAILURE = 'FETCH_CAR_LIST_FAILURE';

export const HANDLE_SEARCH = 'HANDLE_SEARCH';

export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE'